#:kivy 2.1.0

<ScreenCalibration>:
    MDBoxLayout:
        orientation: "vertical"

		# header layout
        MDBoxLayout:
            id: header_layout
            orientation: "horizontal"
            padding: 20
			spacing: 20
			size_hint_y: 0.2
			md_bg_color: "#111111"
                    
            Image:
                id: logo
                source:'assets/images/logo-trb.png'
                size_hint_x: 0.15
                allow_stretch: True 

			MDBoxLayout:
				orientation: "vertical"
				size_hint_x: 0.7

				MDLabel:
					id: lb_title            
					text: "VEHICLE INSPECTION INTEGRATION MANAGEMENT SYSTEM"
					halign: "left"
					valign: "middle"
					font_style: 'H4'
					theme_text_color: "Custom"
					text_color: "#FFFFFF"

				MDLabel:
					id: lb_subtitle            
					text: "VISUAL INSPECTION"
					halign: "left"
					valign: "middle"
					font_style: 'H5'
					theme_text_color: "Custom"
					text_color: "#FFFFFF"

			MDBoxLayout:
				orientation: "vertical"
				size_hint_x: 0.15

				MDLabel:
					id: lb_time
					text: "12:34:00"
					halign: "center"
					valign: "middle"
					font_style: 'H6'
					theme_text_color: "Custom"
					text_color: "#FFFFFF"

				MDLabel:
					id: lb_date
					text: "17/08/2024"
					halign: "center"
					valign: "middle"
					font_style: 'H6'
					theme_text_color: "Custom"
					text_color: "#FFFFFF"

				MDLabel:
					id: lb_operator
					text: "Nama Operator"
					halign: "center"
					valign: "middle"
					font_style: 'H6'
					theme_text_color: "Custom"
					text_color: "#FFFFFF"

				MDLabel:
					id: lb_comm
					text: "Status : Disconnected"
					halign: "center"
					valign: "middle"
					font_style: 'H6'
					theme_text_color: "Custom"

		# main layout
		MDBoxLayout:
			id: layout_main
			orientation: "vertical"
			size_hint_y: 0.7
			padding:20
			spacing:20

			MDBoxLayout:
				id: layout_display
				orientation: "horizontal"
						
				MDBoxLayout:
					orientation: "vertical"
					size_hint_x: 0.5
					padding:20
					spacing:20

					MDBoxLayout:
						orientation: "vertical"
						padding:20
						spacing:20
						
						MDBoxLayout:
							orientation: "horizontal"

							MDLabel:
								text: "SETTING KAMERA UTAMA"
								halign: "center"
								valign: "middle"
								font_style: 'H6'
								size_hint_x: 0.5

						MDBoxLayout:
							orientation: "horizontal"
							MDLabel:
								text: "Kamera Depan"
								halign: "left"
								valign: "middle"
								font_style: 'H6'
								size_hint_x: 0.7

							MDTextField:
								id: tx_set_camera_front
								hint_text: "IP Kamera Depan"
								halign: "left"
								valign: "middle"
								font_style: 'H6'
								size_hint_x: 0.4
								helper_text: "contoh., 192.168.1.100"
								helper_text_mode: "on_focus"
								max_text_length: 15
								text_color_focus: "#4471C4"
								on_text_validate: root.exec_set_camera_front()	

							MDRectangleFlatIconButton:
								id: bt_exec_set_camera_front
								type: "large"
								size_hint_x: 0.3
								icon: "wrench"
								text:"SET"
								text_color: "#EEEEEE"
								md_bg_color: "#2CA02C"
								font_style: 'H6'
								on_press: root.exec_set_camera_front()		

						MDBoxLayout:
							orientation: "horizontal"
							MDLabel:
								text: "Kamera Kiri"
								halign: "left"
								valign: "middle"
								font_style: 'H6'
								size_hint_x: 0.7

							MDTextField:
								id: tx_set_camera_left
								hint_text: "IP Kamera Kiri"
								halign: "left"
								valign: "middle"
								font_style: 'H6'
								size_hint_x: 0.4
								helper_text: "contoh., 192.168.1.100"
								helper_text_mode: "on_focus"
								max_text_length: 15
								text_color_focus: "#4471C4"
								on_text_validate: root.exec_set_camera_left()

							MDRectangleFlatIconButton:
								id: bt_exec_set_camera_left
								type: "large"
								size_hint_x: 0.3
								icon: "wrench"
								text:"SET"
								text_color: "#EEEEEE"
								md_bg_color: "#2CA02C"
								font_style: 'H6'
								on_press: root.exec_set_camera_left()

						MDBoxLayout:
							orientation: "horizontal"
							MDLabel:
								text: "Kamera Kanan"
								halign: "left"
								valign: "middle"
								font_style: 'H6'
								size_hint_x: 0.7

							MDTextField:
								id: tx_set_camera_right
								hint_text: "IP Kamera Kanan"
								halign: "left"
								valign: "middle"
								font_style: 'H6'
								size_hint_x: 0.4
								helper_text: "contoh., 192.168.1.100"
								helper_text_mode: "on_focus"
								max_text_length: 15
								text_color_focus: "#4471C4"
								on_text_validate: root.exec_set_camera_right()

							MDRectangleFlatIconButton:
								id: bt_exec_set_camera_right
								type: "large"
								size_hint_x: 0.3
								icon: "wrench"
								text:"SET"
								text_color: "#EEEEEE"
								md_bg_color: "#2CA02C"
								font_style: 'H6'
								on_press: root.exec_set_camera_right()		

						MDBoxLayout:
							orientation: "horizontal"
							MDLabel:
								text: "Kamera Belakang"
								halign: "left"
								valign: "middle"
								font_style: 'H6'
								size_hint_x: 0.7

							MDTextField:
								id: tx_set_camera_back
								hint_text: "IP Kamera Belakang"
								halign: "left"
								valign: "middle"
								font_style: 'H6'
								size_hint_x: 0.4
								helper_text: "contoh., 192.168.1.100"
								helper_text_mode: "on_focus"
								max_text_length: 15
								text_color_focus: "#4471C4"
								on_text_validate: root.exec_set_camera_back()

							MDRectangleFlatIconButton:
								id: bt_exec_set_camera_back
								type: "large"
								size_hint_x: 0.3
								icon: "wrench"
								text:"SET"
								text_color: "#EEEEEE"
								md_bg_color: "#2CA02C"
								font_style: 'H6'
								on_press: root.exec_set_camera_back()

				MDBoxLayout:
					orientation: "vertical"
					size_hint_x: 0.5
					padding:20
					spacing:20

					MDBoxLayout:
						orientation: "vertical"
						padding:20
						spacing:20
						
						MDBoxLayout:
							orientation: "horizontal"

							MDLabel:
								text: "SETTING KAMERA KOLONG"
								halign: "center"
								valign: "middle"
								font_style: 'H6'
								size_hint_x: 0.5

						MDBoxLayout:
							orientation: "horizontal"
							MDLabel:
								text: "Kamera Kolong Depan"
								halign: "left"
								valign: "middle"
								font_style: 'H6'
								size_hint_x: 0.7

							MDTextField:
								id: tx_set_camera_pit_front
								hint_text: "IP Kamera Kolong Depan"
								halign: "left"
								valign: "middle"
								font_style: 'H6'
								size_hint_x: 0.4
								helper_text: "contoh., 192.168.1.100"
								helper_text_mode: "on_focus"
								max_text_length: 15
								text_color_focus: "#4471C4"
								on_text_validate: root.exec_set_camera_pit_front()	

							MDRectangleFlatIconButton:
								id: bt_exec_set_camera_pit_front
								type: "large"
								size_hint_x: 0.3
								icon: "wrench"
								text:"SET"
								text_color: "#EEEEEE"
								md_bg_color: "#2CA02C"
								font_style: 'H6'
								on_press: root.exec_set_camera_pit_front()		

						MDBoxLayout:
							orientation: "horizontal"
							MDLabel:
								text: "Kamera Kolong Kiri"
								halign: "left"
								valign: "middle"
								font_style: 'H6'
								size_hint_x: 0.7

							MDTextField:
								id: tx_set_camera_pit_left
								hint_text: "IP Kamera Kolong Kiri"
								halign: "left"
								valign: "middle"
								font_style: 'H6'
								size_hint_x: 0.4
								helper_text: "contoh., 192.168.1.100"
								helper_text_mode: "on_focus"
								max_text_length: 15
								text_color_focus: "#4471C4"
								on_text_validate: root.exec_set_camera_pit_left()

							MDRectangleFlatIconButton:
								id: bt_exec_set_camera_pit_left
								type: "large"
								size_hint_x: 0.3
								icon: "wrench"
								text:"SET"
								text_color: "#EEEEEE"
								md_bg_color: "#2CA02C"
								font_style: 'H6'
								on_press: root.exec_set_camera_pit_left()

						MDBoxLayout:
							orientation: "horizontal"
							MDLabel:
								text: "Kamera Kolong Kanan"
								halign: "left"
								valign: "middle"
								font_style: 'H6'
								size_hint_x: 0.7

							MDTextField:
								id: tx_set_camera_pit_right
								hint_text: "IP Kamera Kolong Kanan"
								halign: "left"
								valign: "middle"
								font_style: 'H6'
								size_hint_x: 0.4
								helper_text: "contoh., 192.168.1.100"
								helper_text_mode: "on_focus"
								max_text_length: 15
								text_color_focus: "#4471C4"
								on_text_validate: root.exec_set_camera_pit_right()

							MDRectangleFlatIconButton:
								id: bt_exec_set_camera_pit_right
								type: "large"
								size_hint_x: 0.3
								icon: "wrench"
								text:"SET"
								text_color: "#EEEEEE"
								md_bg_color: "#2CA02C"
								font_style: 'H6'
								on_press: root.exec_set_camera_pit_right()		

						MDBoxLayout:
							orientation: "horizontal"
							MDLabel:
								text: "Kamera Kolong Belakang"
								halign: "left"
								valign: "middle"
								font_style: 'H6'
								size_hint_x: 0.7

							MDTextField:
								id: tx_set_camera_pit_back
								hint_text: "IP Kamera Kolong Belakang"
								halign: "left"
								valign: "middle"
								font_style: 'H6'
								size_hint_x: 0.4
								helper_text: "contoh., 192.168.1.100"
								helper_text_mode: "on_focus"
								max_text_length: 15
								text_color_focus: "#4471C4"
								on_text_validate: root.exec_set_camera_pit_back()

							MDRectangleFlatIconButton:
								id: bt_exec_set_camera_pit_back
								type: "large"
								size_hint_x: 0.3
								icon: "wrench"
								text:"SET"
								text_color: "#EEEEEE"
								md_bg_color: "#2CA02C"
								font_style: 'H6'
								on_press: root.exec_set_camera_pit_back()

			MDBoxLayout:
				orientation: "horizontal"
				spacing: 20
				size_hint_y: 0.02
					
				MDRectangleFlatIconButton:
					id: bt_back
					text: "KEMBALI"
					icon: "arrow-left"
					theme_text_color: "Custom"
					text_color: "#EEEEEE"
					md_bg_color: "4471C4"
					size_hint_x: 0.3
					on_press: root.exec_navigate_main()

		# footer layout
        MDBoxLayout:
            orientation: "horizontal"
			size_hint_y: 0.1

			MDBoxLayout:
				orientation: "horizontal"
				padding: 20
				spacing: 20
				md_bg_color: "#4471C4"
				size_hint_x: 0.4
				
				AsyncImage:
					id: img_pemkab
					source:'assets/images/logo-sorong.png'
					size_hint_x: 0.1
					allow_stretch: True  

				AsyncImage:
					id: img_dishub
					source:'assets/images/logo-dishub.png'
					size_hint_x: 0.1
					allow_stretch: True  

				MDBoxLayout:
					orientation: "vertical"
					size_hint_x: 0.8

					MDLabel:
						id: lb_pemkab
						text: "PEMERINTAH KABUPATEN SORONG"
						halign: "left"
						valign: "middle"
						theme_text_color: "Custom"
						text_color: "#EEEEEE"						
						font_style: 'Subtitle1'

					MDLabel:
						id: lb_dishub
						text: "DINAS PERHUBUNGAN"
						halign: "left"
						valign: "middle"
						theme_text_color: "Custom"
						text_color: "#EEEEEE"
						font_style: 'Subtitle1'

					MDLabel:
						id: lb_unit			
						text: "UNIT PELAKSANA UJI BERKALA KENDARAAN BERMOTOR"
						halign: "left"
						valign: "middle"
						theme_text_color: "Custom"
						text_color: "#EEEEEE"
						font_style: 'Subtitle1'

					MDLabel:
						id: lb_unit_address
						text: " Klamasen, Distrik Mariat, Kabupaten Sorong, Papua Barat Daya. 98416"
						halign: "left"
						valign: "middle"
						md_bg_color: "#EEEEEE"
						theme_text_color: "Custom"
						text_color: "#000000"
						font_style: 'Subtitle1'

			MDBoxLayout:
				orientation: "vertical"
				padding: 20
				spacing: 20
				md_bg_color: "#FFC000"
				size_hint_x: 0.6

				MDLabel:			
					text: "INFORMASI"
					halign: "left"
					valign: "middle"
					font_style: 'H5'

				MDLabel:
					id: lb_info
					text: ""
					halign: "left"
					valign: "middle"
					font_style: 'H6'